### ISSUE TITLE
some questions related to overclocking (MACH and GJD/JED files)

### ISSUE THREAD

**Issue by jdieguez** [na103/GVP_G-Force_030#1]
Hi and thanks for this wonderful repository and also the related nerdone.it blog post.

I own a GVP 030 rev4 40 Mhz and this will definitely be very useful to replace the PALs with GALs and maybe try to overclock it a bit.

I have inspected the jpg of the 40Mhz rev4 card overclocked to 50Mhz and the only differences I can see is that a 50Mhz crystal is used, and that the mach has been burned to another chip (and placed in a socket). All the GALs remain the same as in the 40mhz not-overclocked. 

This raises severral questions:

1) Why the change in the MACH chip? The files corresponding to the mach in 40mhz and 50mhz folders seem to be identical.

2) Is it really not needed to change the GALs? Many users tried to naively overclock their 40Mhz card by just changing the oscillator and they reported that the card does not work, because the PALs/GALs are different for the different card speeds.

3) I see that the only difference between the 040 and 050 JED files seems to be in the U36 IC (90C4 for rev4 40Mhz and 90C6 for rev3 50Mhz). Do you know if the rev4 card would work with the 90C6 IC and what would be the effect?

4) Finally I see that there is a commit related to a rework of the U36-90C6 using WinCUPL, and the resulting JED file seems indeed different to the original GJD uploaded previously (and my programmer reports different checksums when I load the JED and the GJD). What is the purpose of the rework? I guess this has something to do with what is stated in the nerdone blog post:

> "È bene notare che questa tipologia di conversione è una “traduzione” della mappa di bit della Fuse Map: le equazioni non vengono estrapolate, l’ordine dei fattori non viene toccato e non viene eseguito nessun tipo di semplificazione.
> Questo nella maggior parte dei casi può andare benissimo ma come abbiamo visto può essere necessario ottimizzare ulteriormente la programmazione con tool come WinCupl o OPALJR. Ma questa è materia per un altro articolo…"

Thanks again for the project and your time!

**Comment by na103** [comment]
Hello and thank you for your interest and questions.

premise: the work of replacing all the PALs with more modern GALs was born out of the need to repair my friend Luca's GVP 50Mhz (see article on nerdone.it).
In particular, it had a problem on the PAL U36 that made reading/writing operations from SCSI disk to memory unreliable.
As you may have read in the article on nerdone.it I was very lucky because on my 50Mhz GPV, identical in version to Luca's board, all the PALs (or almost all) were not protected and I was thus able to replace them all with GALs.
However, the complete set of GALs that worked without problems on my board continued to give some problems (read/write checksumm error) on Luca's board.
Problem that was solved with a different type of U36 GAL (Atmel) and by rewriting and recompiling the jedfile from Wincupl.
I would like to point out that U36 with GAL Lattice and automatic conversion from jed to gjd works without problems on my board.
From a more careful analysis there are small differences between the two boards, a pullup restisor (r35), the jumpers in different positions, the SCSI performance of Luca's board is superior to mine.
so this could explain the difference.
Apart from this, U36 is at one of the furthest trace points and is therefore more subject to noise and signal attenuation. The gal atmel was probably the type of party least sensitive to the problem and
optimizing the equations with the Wincupl compiler further improved the sensitivity of the logic.

the replacement of the MACH130 U6 was instead born from a repair job on a 40Mhz GVP which broke (almost immediately) after being overclocked to 50Mhz.
After replacing all the PALs with GALs, it started again but still had some problems (booting the workbench from floppy disk only with the scsi controller disabled, freezing after a few seconds at 50mhz) which were then resolved by also replacing the MACH130.
Luckily the MACH130 was only partially fried and I was able to read the contents and then replace it with a NOS one purchased on ebay.
With the new U6 and the GAL set it works fine at 50Mhz just changing the oscillator and CPU/FPU.
It also works using the original PAL set but obviously they heat up a lot.
I found no differences when installing U36 90C6, it works as well as with 90C4 and therefore I left the original one. However, I wouldn't be surprised if in some cases it might be necessary to update it.

concluding the idea I had (it is my opinion and could be wrong) is that GVP in the production of the cards, based on the response of the logical components (PAL and MATCH), could decide if a card was suitable to support 50Mhz or not and if not it would be downgraded and sold as 40Mhz.

**Comment by jdieguez** [comment]
thanks, this clarifies everything.

Your theory regarding not all boards working reliably at 50mhz and being sold as 40mhz, makes perfect sense.

One thing I will not do for the time being is to try to overclock. I don't want to risk frying the MACH, which would be a pain to unsolder and replace :)

But I will just replace the PALs with GALs.

One further question: how were the PALs dumped? I could not find any info about this and I'm interested in trying this myself.

On an unrelated topic, I'm also trying to understand how the registered PAL U701 rev2 from the A3000 could have been dumped, because I this revision PLD is not really found in the Dave Haynie Archives...

**Comment by na103** [comment]
All PAL readings, obviously only unprotected ones, were carried out with a vintage HI-LO ALL-11 programmer.
for protected PALs check this repo: https://github.com/DuPAL-PAL-DUmper/DuPAL_Board.

I think I see the U701 PLD in Dave's archive here.
https://web.archive.org/web/20061001061240/http://www.thule.no/haynie/systems/amiga3k/pals/newmod/u701.pld
Is this the version you were looking for?

**Comment by jdieguez** [comment]
Thanks for the tips! I'll check out both devices. THis PAL hacking stuff really interests me.

As for the U071, I found 3 versions in Dave's archive: rev1, rev3 and rev4. THe last 2 do not even compile (they have a syntax error, at least with CUPL3 and CUPL4 I tried... but Dave used CUPL2 which I could not find).

Anyway, since the chip is named 390528-02 I think the revision which went out in production in real amigas is most likely rev2, for which we don't have the source for.
